# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
env:
    RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }} 
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: BaseApi_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.127.0
        with:
          bundler-cache: true
          ruby-version: 3.2.0
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:create
      - name: Migrate database
        run: bin/rails db:migrate
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

